app:
  kafka:
    enabled: true
  topic:
    name: user_mgmt_to_notification
    partitions: 2
    replica-factor: 1
  application:
    cache:
      expiryInSec: 10800
  secret:
    key: Vfj69nm&^%3KjinRvFVSKJSJKJKhjsd87812jkJKJKLAAJK
  jwt:
    expirationTime: JWT_EXPIRATION_TIME:1734431739
logging:
  level:
    root: INFO