config:
  name: "PROD"
app:
  kafka:
    enabled: true
  topic:
    name: user_mgmt_to_notification
    partitions: 2
    replica-factor: 1
  application:
    cache:
      expiryInSec: 10800
logging:
  level:
    root: INFO